name: Run tests

on:
  push:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Generate docs
      run: go install github.com/swaggo/swag/cmd/swag@latest && go generate .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...